version: '3.8'

services:
  database:
    image: postgres:16.0
    container_name: qr-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    volumes:
    - ./postgres-data:/var/lib/postgresql/data

  gateway:
    container_name: qr-gateway
    build: 
      context: qr-gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  app:
    container_name: qr-app
    build: 
      context: qr-app
      dockerfile: Dockerfile
    ports:
      - "8081:8081"

  dashboard:
    container_name: qr-dashboard
    build: 
      context: qr-dashboard
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
