CREATE TABLE users_info
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name VARCHAR(255),
    last_name  VARCHAR(255),
    nickname   VARCHAR(255),
    CONSTRAINT pk_users_info PRIMARY KEY (id)
);

ALTER TABLE users
    ADD user_info_id BIGINT;

ALTER TABLE users
    ADD CONSTRAINT FK_USERS_ON_USER_INFO FOREIGN KEY (user_info_id) REFERENCES users_info (id);