CREATE TABLE meal_categories
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name          VARCHAR(255),
    restaurant_id BIGINT,
    CONSTRAINT pk_meal_categories PRIMARY KEY (id)
);

CREATE TABLE meal_category
(
    category_id BIGINT NOT NULL,
    meal_id     BIGINT NOT NULL
);

ALTER TABLE meal_categories
    ADD CONSTRAINT FK_MEAL_CATEGORIES_ON_RESTAURANT FOREIGN KEY (restaurant_id) REFERENCES restaurants (id);

ALTER TABLE meal_category
    ADD CONSTRAINT fk_meacat_on_meal FOREIGN KEY (meal_id) REFERENCES meals (id);

ALTER TABLE meal_category
    ADD CONSTRAINT fk_meacat_on_meal_category FOREIGN KEY (category_id) REFERENCES meal_categories (id);